language: en
dictionaries:
  - bash
  - google
  - lorem-ipsum
  - python
  - softwareTerms
words:
  - addopts
  - adoptopenjdk
  - alnum
  - Antora
  - apikey
  - apiserver
  - apiuser
  - applicationsets
  - authc
  - auths
  - autoplay
  - Autotest
  - autotests
  - Autodeploy
  - awsdns
  - AWSIRSA
  - azuread
  - AZUREAD
  - backchannel
  - Beego
  - bitnami
  - Bnow
  - boltdb
  - Bridgecrew
  - buildtool
  - cacerts
  - cbis
  - cbtype
  - ccoctl
  - CDPIPELINE
  - cdstage
  - cdxgen
  - Cfluent
  - changeit
  - changemerged
  - Checkmarx
  - cicd
  - ciuser
  - Civo
  - clastix
  - clusterissuer
  - clusterrole
  - clusterrolebinding
  - cmctl
  - codebasebranch
  - codebasebranches
  - codebaseimagestream
  - codecentric
  - Codemie
  - Codenarc
  - codemie
  - codeviewer
  - commentadded
  - configmap
  - Coverity
  - credrequests
  - creds
  - csanchez
  - daniilnedostup
  - dbchecker
  - dbcleaner
  - deepcopy
  - defectdojo
  - dependencytrack
  - deployers
  - DEPTRACK
  - Djava
  - Djgroups
  - Dkeycloak
  - dockerbuild
  - dockerconfigjson
  - dockerhub
  - dropdb
  - dumpall
  - EBSCSI
  - Entra
  - edpcomponent
  - edpcomponents
  - emptydir
  - endpointshort
  - entra
  - EPAM
  - epamedp
  - epmd
  - externalsecret
  - extrasecrets
  - fastapi
  - Filebeat
  - filesystems
  - finalizer
  - finalizers
  - fluentbit
  - fullname
  - Fzcw
  - gantt
  - gcpsm
  - Gerrit
  - gitfusion
  - GITFUSION
  - gitops
  - Gitserver
  - GITTAG
  - GOPATH
  - GOROOT
  - Grype
  - hadolint
  - harborkeycloakclient
  - hostedzone
  - Hostnames
  - hyperthreading
  - importcert
  - ingresscontroller
  - initdb
  - issueadmin
  - jobservice
  - junitxml
  - Kaniko
  - keepalive
  - Keyacloak
  - Keycloak
  - keycloakauthflow
  - keycloakclient
  - keycloakclientscope
  - keycloakrealm
  - keycloakrealmidentityprovider
  - keycloakrealmrole
  - keycloakrealmrolebatch
  - keycloakrealmuser
  - keycloakx
  - Keycloakx
  - keyid
  - keytool
  - kibanaserver
  - kibanauser
  - krakend
  - krci
  - kubeadmin
  - kubeconfig
  - kubelet
  - kubelogin
  - kuberocketci
  - ldflags
  - lifecycles
  - lintconf
  - listner
  - Logsight
  - ltree
  - Lucene
  - Metasploit
  - Metricbeat
  - Micosoft
  - mkdocs
  - MKNOD
  - mrparkers
  - multitenancy
  - multitenant
  - multivalued
  - mutatingwebhook
  - mykolamarusenko
  - mypipe
  - myuser
  - newcbis
  - newcoming
  - nindent
  - Nlcg
  - noout
  - noprompt
  - nosniff
  - nslookup
  - ojson
  - opensearch
  - Packetbeat
  - parameterstore
  - passwordfile
  - patchset
  - patchsetcreated
  - persistentvolumeclaims
  - persistentvolumes
  - petclinic
  - pgcrypto
  - pgdb
  - PGPASSWORD
  - pipelinerun
  - pipelineruns
  - pipelinetype
  - PKCS
  - preconfigured
  - printenv
  - psql
  - pullrequest
  - pwjps
  - Qualys
  - qualitygate
  - Quarkus
  - rabbitmq
  - rabbitmqctl
  - regcred
  - Rego
  - rekor
  - reportportal
  - resourcetemplates
  - restic
  - rolebindings
  - rolesmapping
  - rpuser
  - SAMEORIGIN
  - SDLC
  - seccomp
  - secretkey
  - secretstore
  - securityhotspotadmin
  - selfsubjectrulesreviews
  - Semgrep
  - sergk
  - serviceaccount
  - serviceaccounts
  - serviceanalyzer
  - serviceanalyzertrain
  - serviceapi
  - serviceindex
  - serviceui
  - SETGID
  - SETUID
  - SLSA
  - slsaprovenance
  - Snyk
  - sonarqube
  - sonarsource
  - Sonatype
  - sshkey
  - sshport
  - statefulset
  - storageclass
  - storepass
  - struct
  - subresource
  - superadmin
  - Sysdig
  - tablespaces
  - tanzu
  - Taskrun
  - tekton
  - tfenv
  - tflint
  - Tflint
  - tfsec
  - Tfsec
  - tfstate
  - tfvars
  - tolerations
  - toolset
  - traefik
  - trgm
  - triggertemplate
  - trustcacerts
  - truststore
  - usedomainname
  - USEDOMAINNAME
  - userinfo
  - usermodel
  - vacuumdb
  - velero
  - Veracode
  - verion
  - wafv
  - waynesun
  - wildfly
  - Wildfly
  - xlarge
  - zwpj
  - Karpenter
  - karpenter
  - tomap
  - nodepools
  - nodepool
  - nodeclasses
  - fasapi
  - applicationset
  - applicationsetcontroller
  - rolearn
  - eksadminrole
  - rolebinding
  - —Åontrol
enableFiletypes:
  - md
  - mdx
ignorePaths:
  - .git
  - .github
  - .idea
  - .log
  - .png
  - .svg
  - .vscode
  - buid
  - node_modules
  - "**/api/**"
